### ISSUE TITLE
Running Unit Tests with the mocked class

### ISSUE THREAD

**Issue by zichaelpath** [mat007/turtle#100]
Hello,
I am currently testing a feature of software that requires a hardware component, and my solution to that was to create a partially mocked class of the class being tested in order to control the outcome of the derived classes private functions.  While running that test suite individually, I get no errors in the tests of that suite; however when I run all the test suites, the tests after that test suite is completed gives me an "invalid parameter detected by a C Runtime Library".

My issue is that this circumstance is causing all the other tests after this suite to fail with our own error system, however removing the test suite with the mocked class being tested causes all the other suites to run as expected and pass.

Are we able to test a partially mocked class and run all the boost tests without the latter suites crashing?

**Comment by mat007** [comment]
Hi,

It’s a bit hard to debug without seeing the code. Would you be able to provide a minimal example reproducing the problem?

**Comment by zichaelpath** [comment]
Absolutely I can, is there any chance you can give me an email to send the sample code to?  I'm having difficulty uploading it to github at the moment

**Comment by mat007** [comment]
Hey, I don’t remember if I ever gave you my email in the end, sorry about that.
Do you still need help? 😬
