### ISSUE TITLE
Remove support for BOOST_IDENTITY_TYPE

### ISSUE THREAD

**Issue by Flamefire** [mat007/turtle#109]
I recently introduced `MOCK_PROTECT_FUNCTION_SIG` serving the same purpose but with a much clearer name. Oh and the benefit of avoiding an extra level of braces: 
```
    MOCK_METHOD(method, 0, MOCK_PROTECT_FUNCTION_SIG(std::map<int, int>()))
    MOCK_METHOD(method, 0, BOOST_IDENTITY_TYPE((std::map<int, int>())))
```

As part of the breaking change-containing release we could remove support for passing stuff via `BOOST_IDENTITY_TYPE` which removes the need for the `MOCK_FUNCTION_TYPE`-macro making the code much cleaner.

Example usages:
```
#define MOCK_FUNCTOR(name, ...) mock::detail::functor<MOCK_FUNCTION_TYPE(__VA_ARGS__)> name, name##_mock
#define MOCK_PARAM(S) mock::detail::parameter_t < MOCK_FUNCTION_TYPE(S)
#define MOCK_DECL(M, n, S, c) mock::detail::result_type_t<MOCK_FUNCTION_TYPE(S)> M(MOCK_DECL_PARAMS(n, S)) c
```

@mat007 Objections?

**Comment by mat007** [comment]
Sure, sounds good!
