### ISSUE TITLE
Any upcoming release?

### ISSUE THREAD

**Issue by jonesmz** [mat007/turtle#121]
It's been a while, and i see there are lots of things merged.

Just wondering what the stability of the current main branch is and if a release is suitable?

**Comment by mat007** [comment]
Hey,

Yes, that’s a fair point. I’ll take a look over the week-end!

**Comment by Flamefire** [comment]
Yes I guess a 2.0.0 release is warranted as C++14 is now a requirement.

**Comment by mat007** [comment]
Done: https://github.com/mat007/turtle/releases/tag/v2.0.0!

**Comment by LegalizeAdulthood** [comment]
The sourceforge documentation doesn't appear to have been updated?  No 2.0 changelog listed, at least.

**Comment by mat007** [comment]
> The sourceforge documentation doesn't appear to have been updated? No 2.0 changelog listed, at least.

Indeed, good catch! 🤦

**Comment by mat007** [comment]
Fixed now, thanks!
