### ISSUE TITLE
logging thread safety

### ISSUE THREAD

**Issue by sebkraemer** [mat007/turtle#47]
Hi there. Thank you for providing turtle mock!

I ran into an issue when I used a mock class in worker threads. Using `MOCK_THREAD_SAFE` solved the first part but there were race conditions. Turns out that the problem is not in turtle itself but in the lack of thread safety of the boost logging framework: Mock expectations were logged concurrently with `BOOST_CHECK` output for example.
My _workaround_ is to reduce log level to error but I'm interested if there is a workable solution which solves this problem.

I used turtle mock master (d7b1ad08008e57b6f25c587aa9eef2e750d66e33) and boost 1.64 with gcc 6.2 x64 and MSVC 19.0.24210.0 x64.

**Comment by mat007** [comment]
Hi,

Are you seeing races in logs originating from turtle?
`MOCK_THREAD_SAFE` is also supposed to add locks for these calls, are you seeing a bug there?

However I'm afraid there is little that can be done for manual logs (or `BOOST_CHECK*°` as you mention) made from the test code outside of turtle…

**Comment by sebkraemer** [comment]
Hey. I don't see a bug in turtle itself. The race I witnessed was between an automatic mock expectation log and a log from BOOST_CHECK macro in my test suite code.
I was afraid this was not solvable by changing turtle mock but I wanted to be sure. In this case, maybe it's woth a not in the manual. Also, could it be an option to being able to disable logging only inside turtle?

**Comment by mat007** [comment]
For altering the logging behavior the recommended way is to provide a custom mock policy as described in [Test framework integration](http://turtle.sourceforge.net/turtle/customization.html#turtle.customization.test_framework_integration). This way you have full control over what and how you log.
Just use [turtle/error.hpp](https://github.com/mat007/turtle/blob/master/include/turtle/error.hpp) as a starting point and it should cover your use case, I believe ?

**Comment by sebkraemer** [comment]
Yes, using my own policy did the trick to decouple logging, thank you!
