### ISSUE TITLE
turtle/mock.hpp causing error because of missing boost/test/utils/trivial_singleton.hpp

### ISSUE THREAD

**Issue by MartinBeseda** [mat007/turtle#50]
Hello,
I wanted to use Turtle library to create mock objects for Boost.
The problem is, that when I include` turtle/mock.hpp`, then I'm getting the following error:
`fatal error: boost/test/utils/trivial_singleton.hpp: No such file or directory`

I've found out, that `trivial_singleton.hpp` was removed from Boost.Test library - see
[this commit](https://github.com/boostorg/test/commit/e021ca8b68c6cdff47808ec5a29df62642c988e9).

So, is it possible to fix this problem in Turtle? I'd love to use it, as it seems really easy and is developed to be used with Boost, which I rely on heavily in my project.

Thank you very much.

Best regards,
Martin

**Comment by mat007** [comment]
Hi Martin,

It seems the code has now moved into the `detail` section of the boost test library…
The easiest as far as turtle is concerned would be to duplicate it into a `turtle/detail/singleton.hpp` and not rely on boost test anymore. The macros will have to be adjusted as well (e.g. `BOOST_TEST_SINGLETON_INST` -> `MOCK_SINGLETON_INST`, etc…).

I'll try and see if I can find a bit of time to do that (I don't work with C++ anymore and don't have any C++ compiler installed at the moment).
Or as this looks like a simple code change, if you wanted to make a PR for it I could make a release after that.

**Comment by MartinBeseda** [comment]
Hi Matt,
I believe, that @sejd0n solved this issue.

**Comment by MartinBeseda** [comment]
Hi Matt,
did you have any time to look at the PR?

**Comment by mat007** [comment]
Fixed by #55
