### ISSUE TITLE
Travis builds not working

### ISSUE THREAD

**Issue by Flamefire** [mat007/turtle#52]
The last travis build of master was 2 years ago: https://travis-ci.org/mat007/turtle/branches

Is it disabled or so?

**Comment by mat007** [comment]
Yeah, CI is in a bad state, I started https://github.com/mat007/turtle/pull/45 to try and fix it a few months ago but the combination of compilers and boost versions made it really annoying…

**Comment by mat007** [comment]
Ah right, no that's not intentional, trying to fix that with #45 as well.
Thanks!
