### ISSUE TITLE
C++98 compatibility broken

### ISSUE THREAD

**Issue by Flamefire** [mat007/turtle#53]
This commit breaks C++98 compatibility by using `std::move` and r-value references: https://github.com/mat007/turtle/pull/41/commits/caef00d2e315cda0697ebf79c4bade888aa9b17d

**Comment by mat007** [comment]
Thanks for noticing this!
Are you actually building in C++98? I seriously considered dropping support for it a few months ago given that a good chunk of the CI failures and of my time looking for workarounds was due to maintaining this compatibility…

**Comment by Flamefire** [comment]
Unfortunately yes. I'm a maintainer of https://github.com/Return-To-The-Roots/s25client and we have an OSX cross compiler based on an old GCC version that is not C++11 compatible. We are in the process of finding a solution but currently stuck with that.

**Comment by mat007** [comment]
Fixed by #59
