### ISSUE TITLE
Make appveyor build only latest commit

### ISSUE THREAD

**Issue by Flamefire** [mat007/turtle#65]
Appveyor is pretty slow. Hence it should not build outdated commits. Look at the current history: 6h per build, a few hours till each build start stalls the whole CI.

**Comment by Flamefire** [comment]
@mat007 *ping* on this. Check the appveyor GUI for "rolling builds" which can only be enabled through GUI.

**Comment by mat007** [comment]
Makes sense, I just enabled this for `turtle`.
Thanks!

**Comment by Flamefire** [comment]
Can you do the same for travis? It is called " Auto Cancellation " there :)

**Comment by mat007** [comment]
It’s already enabled on Travis:

![image](https://user-images.githubusercontent.com/2386884/71541569-51d68f00-295b-11ea-9d14-f9ae89fc8d87.png)

**Comment by Flamefire** [comment]
Oh, ok. Then maybe it was just a flake I've seen or I was to impatient ;)
