### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by sarum9in** [mat007/turtle#70]
Hi there,
unfortunately 1.3.0 from https://sourceforge.net/projects/turtle/files/ is no longer compatible with recent boost version `1.69.0`, git version is. In order to depend on this library in a project having a version would help a lot. Would you mind creating a release?
Thank you!

**Comment by mat007** [comment]
Oh yes, I believe a release is long overdue, I'll try and find some time later today to do that.
Thanks!

**Comment by BloggerBust** [comment]
Have you thought about seeing if the [Boost community](https://www.boost.org/community/) would be interested in maintaining it as an official library?

**Comment by sarum9in** [comment]
Bump :)

**Comment by mat007** [comment]
> Have you thought about seeing if the Boost community would be interested in maintaining it as an official library?

I did at some point, see http://boost.2283326.n4.nabble.com/Boost-Mock-td4651734.html
I kind of lost the motivation in the meanwhile :)

Anyway, here is a new release here https://sourceforge.net/projects/turtle/files/turtle/1.3.1/ and there as well https://github.com/mat007/turtle/releases/tag/v1.3.1.

**Comment by BloggerBust** [comment]
Thank you mat007. Also, I understand about loosing interest due to lack of incentive. If my project goes somewhere then I might be interested in contributing, but right now the little bit of time I have is focused elsewhere. Thanks again for the release.
