### ISSUE TITLE
program is grabbing the non mocked class as opposed to the mocked class

### ISSUE THREAD

**Issue by zichaelpath** [mat007/turtle#75]
Hi there,
First of, let me just say that your program has made my job MUCH easier over the past month since I started using it, so kudos to you.  I'm having an issue where I have created a mocked class and am attempting to use the mocked class in a unit test, however the test environment keeps using the base class.  I have attempted to create the mock class in two ways:
1) using MOCK_BASE_CLASS
2) creating the class normally, but calling MOCK_METHOD for each function I am mocking
I have done this for several other classes and those mock objects still work perfectly fine, however this class is behaving strangely.  Do you have any advice on how to proceed?

**Comment by mat007** [comment]
Hi!

Can you make a minimal reproducible case that I can take a look at?

Thanks!
