### ISSUE TITLE
MOCK_CONST_METHOD requires signature while MOCK_METHOD does not

### ISSUE THREAD

**Issue by Flamefire** [mat007/turtle#93]
Is there are specific reason why those macros are so different in their definition?:

```
#define MOCK_METHOD(M, ...) \
    MOCK_METHOD_EXT(M, \
        MOCK_VARIADIC_ELEM_0(__VA_ARGS__, ), \
        MOCK_VARIADIC_ELEM_1(__VA_ARGS__, MOCK_SIGNATURE(M), ), \
        MOCK_VARIADIC_ELEM_2(__VA_ARGS__, M, M, ))
#define MOCK_CONST_METHOD(M, n, ...) \
    MOCK_CONST_METHOD_EXT(M, n, \
        MOCK_VARIADIC_ELEM_0(__VA_ARGS__, ), \
        MOCK_VARIADIC_ELEM_1(__VA_ARGS__, M, ))
#define MOCK_NON_CONST_METHOD(M, n, ...) \
    MOCK_NON_CONST_METHOD_EXT(M, n, \
        MOCK_VARIADIC_ELEM_0(__VA_ARGS__, ), \
        MOCK_VARIADIC_ELEM_1(__VA_ARGS__, M, ))
```

I would have expected that `MOCK_METHOD` is implemented in terms of the other 2 but it seems that the state between the const and non-const versions is shared. But why does the first auto-detect the signature and the other 2 don't?

**Comment by mat007** [comment]
I’m not sure why there was a difference, probably an oversight when this was introduced…
Anyway, nice catch, thanks!
