### ISSUE TITLE
deprecation message with boost 1.74.0

### ISSUE THREAD

**Issue by TorpedoZoidberg** [mat007/turtle#98]
Using turtle 1.3.2 with boost 1.74.0 (compiler msvc 14.2) there is deprecation message triggered from .../boost/bind.hpp (@line 36) by including the following headers:

#include <boost/test/unit_test.hpp>
#include <turtle/mock.hpp>

The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.

Although technically not a warning it clutters the build output in the same way.

**Comment by Flamefire** [comment]
Fixed with https://github.com/mat007/turtle/pull/88
